# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: email_exchange.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x65mail_exchange.proto\"#\n\x12\x45mailParserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"\'\n\x13\x45mailParserResponse\x12\x10\n\x08received\x18\x01 \x01(\x08\x32L\n\rEmailExchange\x12;\n\x0cSendToParser\x12\x13.EmailParserRequest\x1a\x14.EmailParserResponse\"\x00\x62\x06proto3')



_EMAILPARSERREQUEST = DESCRIPTOR.message_types_by_name['EmailParserRequest']
_EMAILPARSERRESPONSE = DESCRIPTOR.message_types_by_name['EmailParserResponse']
EmailParserRequest = _reflection.GeneratedProtocolMessageType('EmailParserRequest', (_message.Message,), {
  'DESCRIPTOR' : _EMAILPARSERREQUEST,
  '__module__' : 'email_exchange_pb2'
  # @@protoc_insertion_point(class_scope:EmailParserRequest)
  })
_sym_db.RegisterMessage(EmailParserRequest)

EmailParserResponse = _reflection.GeneratedProtocolMessageType('EmailParserResponse', (_message.Message,), {
  'DESCRIPTOR' : _EMAILPARSERRESPONSE,
  '__module__' : 'email_exchange_pb2'
  # @@protoc_insertion_point(class_scope:EmailParserResponse)
  })
_sym_db.RegisterMessage(EmailParserResponse)

_EMAILEXCHANGE = DESCRIPTOR.services_by_name['EmailExchange']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMAILPARSERREQUEST._serialized_start=24
  _EMAILPARSERREQUEST._serialized_end=59
  _EMAILPARSERRESPONSE._serialized_start=61
  _EMAILPARSERRESPONSE._serialized_end=100
  _EMAILEXCHANGE._serialized_start=102
  _EMAILEXCHANGE._serialized_end=178
# @@protoc_insertion_point(module_scope)
