# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import email_exchange_pb2 as email__exchange__pb2


class EmailExchangeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendToParser = channel.unary_unary(
                '/EmailExchange/SendToParser',
                request_serializer=email__exchange__pb2.EmailParserRequest.SerializeToString,
                response_deserializer=email__exchange__pb2.EmailParserResponse.FromString,
                )


class EmailExchangeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendToParser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmailExchangeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendToParser': grpc.unary_unary_rpc_method_handler(
                    servicer.SendToParser,
                    request_deserializer=email__exchange__pb2.EmailParserRequest.FromString,
                    response_serializer=email__exchange__pb2.EmailParserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'EmailExchange', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EmailExchange(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendToParser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/EmailExchange/SendToParser',
            email__exchange__pb2.EmailParserRequest.SerializeToString,
            email__exchange__pb2.EmailParserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
